version: '3.8'

volumes:
  local_postgres_data: {}

services:
  postgres:
    image: postgres:11.12
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
    env_file:
      - ./.envs/.local/.postgres

  app:
    build: API
    command: flask run --host 0.0.0.0
    depends_on:
      - postgres
    env_file:
      - ./.envs/.local/.postgres

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
