version: '3.8'

services:
  rabbitmq:
    hostname: rabbit
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  worker:
    image: us-east1-docker.pkg.dev/andes-384517/compressor-api/api:latest
    command: celery -A compressor.celery_app:app worker
    environment:
      FLASK_APP: compressor.app:create_app
      APP_SETTINGS: compressor.config.DevelopmentConfig
      FLASK_DEBUG: 1
    depends_on:
      - rabbitmq
    env_file:
      - ./.envs/.local/.flask

#  flower:
#    build: .
#    command: celery -A compressor.celery_app:app flower
#    environment:
#      FLASK_APP: compressor.app:create_app
#      APP_SETTINGS: compressor.config.DevelopmentConfig
#      FLASK_DEBUG: 1
#    ports:
#      - "5555:5555"
#    env_file:
#      - ./.envs/.local/.flask
#    depends_on:
#      - rabbitmq
#      - worker