version: '3.8'

services:
  rabbitmq:
    hostname: rabbit
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  worker:
    build: .
    command: celery -A compressor.celery_app:app worker
    environment:
      FLASK_APP: compressor.app:create_app
      APP_SETTINGS: compressor.config.DevelopmentConfig
      FLASK_DEBUG: 1
    depends_on:
      - rabbitmq
    env_file:
      - ./.envs/.local/.flask
    volumes:
      - /mnt/nfs:/code/compressor/files
