"""empty message

Revision ID: 3903c526fa69
Revises: 642e0ae5b042
Create Date: 2023-04-15 19:51:54.235347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3903c526fa69'
down_revision = '642e0ae5b042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=True),
    sa.Column('old_format', sa.String(length=5), nullable=True),
    sa.Column('new_format', sa.String(length=5), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSED', name='taskstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
