"""empty message

Revision ID: b61472f4a435
Revises: 3903c526fa69
Create Date: 2023-04-15 21:28:24.047851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b61472f4a435'
down_revision = '3903c526fa69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    # ### end Alembic commands ###
